### ISSUE TITLE
Default values for minItems, maxItems and move.

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-flexslider#120]
When creating a new slider, this seems to not have anything set which causes an error and the slider doesn't work.

https://github.com/dynamic/silverstripe-flexslider/blob/2.0/code/FlexSlider.php#L156-L158

![image](https://user-images.githubusercontent.com/3858661/29373966-713f6bda-8275-11e7-92f9-516fdb159888.png)

**Comment by muskie9** [comment]
The issue seems to be that existing classes that have `FlexSlider` implemented don't generate the default values. I also ran into an issue when testing on a fresh 3.6.1 installation related to this: `[Warning] A non-numeric value encountered`. This error is due to the fact that the defaults aren't implemented on the existing record.

**Comment by muskie9** [comment]
I think we need to update documentation for this. The task at `dev/tasks/SlideThumbnailNavMigrationTask` will resolve the issue, but we only mention it as a [Pre-release migration task](https://github.com/dynamic/silverstripe-flexslider#pre-release-migration-task). We should update the documentation to note that the task should be run when the module is installed on existing sites and/or when flexslider is applied to existing records. New records will receive the defaults upon creation, but existing records need the task to apply them.

**Comment by muskie9** [comment]
resolved via #121
